In [2]:
import pandas as pd
import pandas as pd
from sqlalchemy import create_engine
import requests
import json
import pandas as pd
import wbgapi as wb
import time
import sys
sys.path.append('..')  # Add the parent directory to the system path

from object import DOCUMENT_URL, PROJECT_URL, PROJECT_COLUMNS, COUNTRY_COLUMNS
from function import get_project

# country from project api pull

In [10]:

# Create the database engine
engine = create_engine('mysql+pymysql://root:root@localhost/wb_proj_doc')


all_projects = {col: [] for col in COUNTRY_COLUMNS}  # ← init with same structure
offset = 0
total = 27848 #do 1000 for testing, but total is 27848

while offset < total:
    data = get_project(COUNTRY_COLUMNS, rows=1000, os=offset)
    if data is None:
        print(f"Skipping offset={offset} after failed retries")
        offset += 1000
        continue

    good_data = data['projects']

    for proj_id, proj in good_data.items():
        for col in COUNTRY_COLUMNS:
            all_projects[col].append(proj.get(col))  # ← append directly into all_projects

    offset += 1000

print(f"Done: {len(next(iter(all_projects.values())))} projects")

country_df = pd.DataFrame(all_projects)

Done: 27872 projects

In [16]:
country_df = country_df[['countryshortname', 'regionname']].copy()
mask = country_df['countryshortname'] == country_df['regionname']
country_df.loc[mask, 'regionname'] = None
country_df = country_df.drop_duplicates(subset=['countryshortname'])
country_df

      countryshortname                   regionname
0             Colombia  Latin America and Caribbean
1              Turkiye      Europe and Central Asia
2            Indonesia        East Asia and Pacific
3          Philippines        East Asia and Pacific
5               Brazil  Latin America and Caribbean
...                ...                          ...
26897        Australia        East Asia and Pacific
27049          Belgium      Europe and Central Asia
27060      Netherlands      Europe and Central Asia
27223       Luxembourg      Europe and Central Asia
27226           France      Europe and Central Asia

[217 rows x 2 columns]

# general project table

In [3]:


all_projects = {col: [] for col in PROJECT_COLUMNS}  # ← init with same structure
offset = 0
total = 27848 #do 1000 for testing, but total is 27848

while offset < total:
    data = get_project(PROJECT_COLUMNS, rows=1000, os=offset)
    if data is None:
        print(f"Skipping offset={offset} after failed retries")
        offset += 1000
        continue

    good_data = data['projects']

    for proj_id, proj in good_data.items():
        for col in PROJECT_COLUMNS:
            all_projects[col].append(proj.get(col))  # ← append directly into all_projects

    offset += 1000

print(f"Done: {len(next(iter(all_projects.values())))} projects")

project_df = pd.DataFrame(all_projects)

Error 500 at os=5000, attempt 1/3
Error 500 at os=20000, attempt 1/3
Error 500 at os=20000, attempt 2/3
Error 500 at os=22000, attempt 1/3
Error 500 at os=25000, attempt 1/3
Error 500 at os=27000, attempt 1/3
Done: 27872 projects

In [5]:
project_df.rename(columns={'id': 'project_id'}, inplace=True)
project_df

,project_id,project_name,countryshortname,borrower,impagency,curr_ibrd_commitment,idacommamt,totalamt,grantamt,lendprojectcost,boardapprovaldate,closingdate,envassesmentcategorycode
0,P508450,"Plan PAZcifico Continuity: Water, Sanitation a...",Colombia,Fiduprevisora,Ministerio de Igualdad y Equidad,205600000,0,205600000,0,None,2027-05-14T00:00:00Z,2032-07-31,None
1,P509929,Second Energy Efficiency in Public Buildings u...,Turkiye,None,None,None,None,None,5000000,None,2027-03-30T00:00:00Z,None,None
2,P515373,Food and Irrigation Security Project,Indonesia,Ministry of Finance,Directorate of Water Resources Management Syst...,500000000,0,500000000,0,501249984,2027-02-26T00:00:00Z,2032-03-31,None
3,P514745,"THRIVE - Technology-driven, Human-centered cli...",Philippines,Department of Finance,Department of Science and Technology,250000000,0,250000000,0,250000000,2027-02-25T00:00:00Z,2032-03-01,None
4,P507827,Philippines SME COMPETE,Philippines,Department of Finance,Department of Trade and Industry (DTI),305000000,0,305000000,0,None,2027-02-25T00:00:00Z,2032-02-22,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27867,P001694,MOPTI RICE SUPPLEMEN,Mali,None,None,0,2600000,2600000,0,0,None,None,None
27868,P001269,RURAL WATER SUPPLY I,Kenya,None,None,None,None,None,None,0,None,1985-06-30,None
27869,P000851,INDUSTRY II CIMAO,Ghana,None,None,20000000,0,20000000,0,0,None,None,None
27870,P000412,BASIC ED.IMPROV.PROJ,Cameroon,None,None,0,20000000,20000000,0,30000000,None,None,C
27871,P000256,RAILWAYS,Burkina Faso,None,None,0,5200000,5200000,0,0,None,None,None